---
title: "Day 26"
author: "Taylor R. Brown"
date: "1/10/2020"
output: slidy_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Roadmap

9.3

- sequential importance sampling with resampling (single-step analysis)

9.4

- **sequential importance sampling with resampling (multi-step analysis)**

There's only one theorem for this particular section, but it comes in two parts. 


## Theorem 9.4.5

Assume:

- Assumption 9.4.1:

  1. $\nu(g_0) > 0$;

  2. $\int_{\mathsf{X}} Q(x,dx') g_k(x') > 0$ (for all $x \in \mathsf{X}$ and $k \ge 1$)

  3. for all $k \ge 0$, $\sup_x g_k(x) < \infty$.

- Assumption 9.4.2

  1. $\phi_{\nu,0} \ll \rho_0$
  
- Assumption 9.4.3

  1. For any time $k \ge 1$, and for all $x \in \mathsf{X}$, $T^u_k(x, \cdot) \ll R_k(x, \cdot)$. Also, for all $x \in \mathsf{X}$, there exists a positive version $\frac{d T^u_k(x, \cdot)}{R_k(x, \cdot)}(x')$ such that
$$
\sup_{(x,x')} \frac{d T^u_k(x, \cdot)}{dR_k(x, \cdot)}(x') < \infty
$$

then...

## Theorem 9.4.5


1. If $\{(\xi^{N,i}_0,  1)\}_{1 \le i \le M_N}$ is consistent for $(\phi_{\nu,0}, L^1(\mathsf{X}, \phi_{\nu,0}))$, then for any $k > 0$ $\{(\xi^{N,i}_k,  1)\}_{1 \le i \le M_N}$ is consistent for $(\phi_{\nu,k}, L^1(\mathsf{X}, \phi_{\nu,k}))$

## Theorem 9.4.5


1. If $\{(\xi^{N,i}_0,  1)\}_{1 \le i \le M_N}$ is consistent for $(\phi_{\nu,0}, L^1(\mathsf{X}, \phi_{\nu,0}))$, then for any $k > 0$ $\{(\xi^{N,i}_k,  1)\}_{1 \le i \le M_N}$ is consistent for $(\phi_{\nu,k}, L^1(\mathsf{X}, \phi_{\nu,k}))$

2. If in addition to the above $\{(\xi^{N,i}_0,  1)\}_{1 \le i \le M_N}$ is asymptotically normal for $(\phi_{\nu,0}, L^2(\mathsf{X}, \phi_{\nu,0}), \sigma_0, \{M_N^{1/2}\})$, then for any $k > 0$ $\{(\xi^{N,i}_k,  1)\}_{1 \le i \le M_N}$ is asymptotically normal for  $(\phi_{\nu,k}, L^2(\mathsf{X}, \phi_{\nu,k}), \sigma_k, \{M_N^{1/2}\})$ where for $f \in L^2(\mathsf{X}, \phi_{\nu,k})$

$$
\sigma_k^2(f) = \text{Var}_{\phi_{\nu,k}}(f) + 
\frac{\sigma^2_{k-1}\left[ T_{k-1}^u \left( f - \phi_{\nu,k}(f) \right) \right] + \alpha^{-1}\eta^2_{k-1}\left[ \left( f - \phi_{\nu,k}(f) \right)^2  \right]}{\left(\phi_{\nu,k-1}T^u_{k-1}(\mathsf{X}) \right)^2}
$$
where
\begin{align*}
\eta^2_{k-1}(f) &= \iint \phi_{\nu,k-1}(dx) R_{k-1}(x,dx')\left\{ \frac{dT_{k-1}^u (x,\cdot)}{dR_{k-1}(x,\cdot)}(x') f(x') \right\}^2 \\
&\hspace{6mm} - \iint \phi_{\nu,k-1}(dx) \left\{ T_{k-1}^u(x,f)\right\}^2
\end{align*}


## Theorem 9.4.5: proof 

We prove everything in the document `tex/proof_9.4.5.pdf`
