---
title: "SISR Proof Sketch"
author: "taylor"
date: "April 26, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Statement to Prove

Assume:

- Assumption 9.4.1:

  1. $\nu(g_0) > 0$;

  2. $T^u_k(x, \mathsf{X}) = \int_{\mathsf{X}} Q(x,dx') g_k(x') > 0$ (for all $x \in \mathsf{X}$ and $k \ge 1$)

  3. for all $k \ge 0$, $\sup_x g_k(x) < \infty$.

- Assumption 9.4.2

  1. $\phi_{\nu,0} \ll \rho_0$
  
- Assumption 9.4.3

  1. For any time $k \ge 1$, and for all $x \in \mathsf{X}$, $T^u_k(x, \cdot) \ll R_k(x, \cdot)$. Also, for all $x \in \mathsf{X}$, there exists a positive version $\frac{d T^u_k(x, \cdot)}{R_k(x, \cdot)}(x')$ such that
$$
\sup_{(x,x')} \frac{d T^u_k(x, \cdot)}{dR_k(x, \cdot)}(x') < \infty
$$

Then

1. If $\{(\xi^{N,i}_0,  1)\}_{1 \le i \le M_N}$ is consistent for $(\phi_{\nu,0}, L^1(\mathsf{X}, \phi_{\nu,0}))$, then for any $k > 0$ $\{(\xi^{N,i}_k,  1)\}_{1 \le i \le M_N}$ is consistent for $(\phi_{\nu,k}, L^1(\mathsf{X}, \phi_{\nu,k}))$

2. If in addition to the above $\{(\xi^{N,i}_0,  1)\}_{1 \le i \le M_N}$ is asymptotically normal for $(\phi_{\nu,0}, L^2(\mathsf{X}, \phi_{\nu,0}), \sigma_0, \{M_N^{1/2}\})$, then for any $k > 0$ $\{(\xi^{N,i}_k,  1)\}_{1 \le i \le M_N}$ is asymptotically normal for  $(\phi_{\nu,k}, L^2(\mathsf{X}, \phi_{\nu,k}), \sigma_k, \{M_N^{1/2}\})$ where for $f \in L^2(\mathsf{X}, \phi_{\nu,k})$

$$
\sigma_k^2(f) = \text{Var}_{\phi_{\nu,k}}(f) + 
\frac{\sigma^2_{k-1}\left[ T_{k-1}^u \left( f - \phi_{\nu,k}(f) \right) \right] + \alpha^{-1}\eta^2_{k-1}\left[ \left( f - \phi_{\nu,k}(f) \right)^2  \right]}{\left(\phi_{\nu,k-1}T^u_{k-1}(\mathsf{X}) \right)^2}
$$
where
\begin{align*}
\eta^2_{k-1}(f) &= \iint \phi_{\nu,k-1}(dx) R_{k-1}(x,dx')\left\{ \frac{dT_{k-1}^u (x,\cdot)}{dR_{k-1}(x,\cdot)}(x') f(x') \right\}^2 \\
&\hspace{6mm} - \iint \phi_{\nu,k-1}(dx) \left\{ T_{k-1}^u(x,f)\right\}^2
\end{align*}


# Proving Part 1: Consistency

Assume $\{(\xi^{N,i}_{k-1},  1)\}_{1 \le i \le M_N}$ is consistent for $(\phi_{\nu,k-1}, L^1(\mathsf{X}, \phi_{\nu,k-1}))$. We want to show that this implies
$\{(\xi^{N,i}_{k},  1)\}_{1 \le i \le M_N}$ is consistent for $(\phi_{\nu,k}, L^1(\mathsf{X}, \phi_{\nu,k}))$.


## Step 1: Mutation


Pick $f \in L^1(\mathsf{X}, \phi_{\nu,k}))$. We have

$$
0 \le \phi_{\nu,k}(|f|) = \frac{\phi_{\nu,k-1} T_{k-1}^u \left(|f| \right)}{\phi_{\nu,k-1}T_{k-1}^u(\mathsf{X}) } < \infty.
$$

Assumption 9.4.1 implies the denominator is finite, so
$$
\phi_{\nu,k-1} T_{k-1}^u \left(|f| \right) < \infty
$$
which means $T_{k-1}^u \left(x,|f| \right) \in L^1(\mathsf{X}, \phi_{\nu,k-1})$. Also, $1 \in L^1(\mathsf{X}, \phi_{\nu,k}))$ so $T_{k-1}^u \left(x,\mathsf{X} \right) \in L^1(\mathsf{X}, \phi_{\nu,k-1})$ as well.

First, 

$$
\sum_{j=1}^{\tilde{M}_N} \frac{\tilde{\omega}^{N,j} }{\sum_{j'}\tilde{\omega}^{N,j'} } f(\tilde{\xi}^{N,j}) 
= \frac{ \tilde{M}_N^{-1} \sum_{j=1}^{\tilde{M}_N}\tilde{\omega}^{N,j} f(\tilde{\xi}^{N,j}) }{ \tilde{M}_N^{-1} \sum_{j=1}^{\tilde{M}_N}\tilde{\omega}^{N,j}  }
$$

We can rewrite the numerator as 
$$
\tilde{M}_N^{-1} \sum_{j=1}^{\tilde{M}_N}\left\{ \tilde{\omega}^{N,j} f(\tilde{\xi}^{N,j})  -  E\left[ \tilde{\omega}^{N,j} f(\tilde{\xi}^{N,j}) \mid \mathcal{F}_{k-1}^N \right] \right\} + \tilde{M}_N^{-1} \sum_{j=1}^{\tilde{M}_N} E\left[ \tilde{\omega}^{N,j} f(\tilde{\xi}^{N,j}) \mid \mathcal{F}_{k-1}^N \right]
$$

The second term 
$$
\tilde{M}_N^{-1} \sum_{j=1}^{\tilde{M}_N} E\left[ \tilde{\omega}^{N,j} f(\tilde{\xi}^{N,j}) \mid \mathcal{F}^N_{k-1} \right] = M_N^{-1} \sum_{j=1}^{M_N} T_{k-1}^u(\xi_{k-1}^{N,i}, f) \overset{\text{p}}{\to} \phi_{\nu,k-1}T^u_{k-1}(f)
$$
because $T_{k-1}^u \left(x,|f| \right) \in L^1(\mathsf{X}, \phi_{\nu,k-1})$.

The first term 
$$
\tilde{M}_N^{-1} \sum_{j=1}^{\tilde{M}_N}\left\{ \tilde{\omega}^{N,j} f(\tilde{\xi}^{N,j})  -  E\left[ \tilde{\omega}^{N,j} f(\tilde{\xi}^{N,j}) \mid \mathcal{F}_{k-1}^N \right] \right\} \overset{\text{p}}{\to} 0
$$
by 9.5.7. Therefore

$$
\tilde{M}_N^{-1} \sum_{j=1}^{\tilde{M}_N}\tilde{\omega}^{N,j} f(\tilde{\xi}^{N,j}) \overset{\text{p}}{\to} \phi_{\nu,k-1}T^u_{k-1}(f).
$$

Applying exactly the same reasoning to the function $1$ instead of $f$

$$
\tilde{M}_N^{-1} \sum_{j=1}^{\tilde{M}_N}\tilde{\omega}^{N,j}  \overset{\text{p}}{\to} \phi_{\nu,k-1}T^u_{k-1}(\mathsf{X}),
$$

so therefore 


$$
\sum_{j=1}^{\tilde{M}_N} \frac{\tilde{\omega}^{N,j} }{\sum_{j'}\tilde{\omega}^{N,j'} } f(\tilde{\xi}^{N,j}) \overset{\text{p}}{\to} \phi_{\nu,k}(f).
$$


## Step 2: Selection

After the previous step, we have $\{ \tilde{\xi}^{N,j}_k, \tilde{\omega}_k^{N,j} \}_{1 \le j \le \tilde{M}_N}$ is consistent for $(\phi_{\nu,k}, L^1(\mathsf{X}, \phi_{\nu,k}))$. Now we want to show the resampled values
$\{(\xi^{N,i}_{k},  1)\}_{1 \le i \le M_N}$ is consistent for $(\phi_{\nu,k}, L^1(\mathsf{X}, \phi_{\nu,k}))$.

Pick $f \in L^1(\mathsf{X}, \phi_{\nu,k})$ and write the estimator as

$$
M_N^{-1} \sum_{i=1}^{M_N} \left\{ f(\xi^{N,i}_{k}) - E[ f(\xi^{N,i}_{k})  \mid \tilde{\mathcal{F}}^k] \right\} + M_N^{-1} \sum_{i=1}^{M_N} E[ f(\xi^{N,i}_{k})  \mid \tilde{\mathcal{F}}^k] .
$$

The second term

$$
M_N^{-1} \sum_{i=1}^{M_N} E[ f(\xi^{N,i}_{k})  \mid \tilde{\mathcal{F}}^k] = E[ f(\xi^{N,1}_{k})  \mid \tilde{\mathcal{F}}^k]
$$
due to the multinomial sampling being done conditionally iid. That term can be written as

$$
E[ f(\xi^{N,1}_{k})  \mid \tilde{\mathcal{F}}^k] =\sum_{j=1}^{\tilde{M}_N} \frac{\tilde{\omega}^{N,j} }{\sum_{j'}\tilde{\omega}^{N,j'} } f(\tilde{\xi}^{N,j}) 
$$
which is consistent using the previous section's reasoning. The first part 

$$
M_N^{-1} \sum_{i=1}^{M_N} \left\{ f(\xi^{N,i}_{k}) - E[ f(\xi^{N,i}_{k})  \mid \tilde{\mathcal{F}}^k] \right\}
$$
converges to $0$ using 9.5.7.



# Proving Part 2: Asymptotic Normality


Assume the above result, the same starting assumptions, and that 
$\{(\xi^{N,i}_{k-1},  1)\}_{1 \le i \le M_N}$ is asymptotically normal for $(\phi_{\nu,k-1}, L^2(\mathsf{X}, \phi_{\nu,k-1}), \sigma_{k-1}, \{M_N^{1/2}\})$.

We want to show that 

$\{(\xi^{N,i}_k,  1)\}_{1 \le i \le M_N}$ is asymptotically normal for  $(\phi_{\nu,k}, L^2(\mathsf{X}, \phi_{\nu,k}), \sigma_k, \{M_N^{1/2}\})$.


## Step 1: Mutation

We want to show that 
$$
\tilde{M}_N^{1/2} \sum_{j=1}^{\tilde{M}_N} \frac{\tilde{\omega}^{N,j}}{\sum_{j'} \tilde{\omega}^{N,j'}}f(\tilde{\xi}^{N,j}_k) 
=
 \frac{ \tilde{M}_N^{1/2} \sum_{j=1}^{\tilde{M}_N} \frac{\tilde{\omega}^{N,j}}{\tilde{M}_N }f(\tilde{\xi}^{N,j}_k) }{ \frac{\sum_{j'} \tilde{\omega}^{N,j'}}{\tilde{M}_N} }
$$
is asymptotically normal first. Rewrite the numerator as

$$
\tilde{M}_N^{1/2}  \sum_{j=1}^{\tilde{M}_N} \left\{  \frac{ \tilde{\omega}^{N,j}}{\tilde{M}_N }f(\tilde{\xi}^{N,j}_k) - E\left[ \frac{ \tilde{\omega}^{N,j}}{\tilde{M}_N }f(\tilde{\xi}^{N,j}_k) \mid \mathcal{F}^N_{k-1} \right] \right\}
+ \tilde{M}_N^{1/2}\frac{1}{\tilde{M}_N}\sum_{j=1}^{\tilde{M}_N}E\left[\tilde{\omega}^{N,j} f(\tilde{\xi}^{N,j}_k) \mid \mathcal{F}^N_{k-1} \right]
$$

The second piece 
$$
\tilde{M}_N^{1/2}\frac{1}{\tilde{M}_N}\sum_{j=1}^{\tilde{M}_N}E\left[\tilde{\omega}^{N,j} f(\tilde{\xi}^{N,j}_k) \mid \mathcal{F}^N_{k-1} \right] = \tilde{M}_N^{1/2}\frac{1}{M_N}\sum_{j=1}^{M_N}  T^u_{k-1}(\xi_{k-1}^{N,i}, f) 
$$
this quantity isn't asymptotically normal, but 

$$
M_N^{1/2}\frac{1}{M_N}\sum_{j=1}^{M_N}  T^u_{k-1}(\xi_{k-1}^{N,i}, f) 
$$
is as soon as we show $T^u_{k-1}(\xi_{k-1}^{N,i}, f)  \in L^2(\mathsf{X}, \phi_{\nu,k-1})$. This is nonobvious, and the book has a few interesting lines showing why it's true. The asymptotic variance of this part is 
$$
\sigma^2_{k-1}\left[ T_{k-1}^u \left( f - \phi_{\nu,k}(f) \right) \right].
$$


The first piece
$$
\tilde{M}_N^{1/2}  \sum_{j=1}^{\tilde{M}_N} \left\{  \frac{ \tilde{\omega}^{N,j}}{\tilde{M}_N }f(\tilde{\xi}^{N,j}_k) - E\left[ \frac{ \tilde{\omega}^{N,j}}{\tilde{M}_N }f(\tilde{\xi}^{N,j}_k) \mid \mathcal{F}^N_{k-1} \right] \right\} \overset{\text{D}}{\to} \text{Normal}\left(0, \eta^2_{k-1}\left[ \left( f - \phi_{\nu,k}(f) \right)^2  \right] \right)
$$
using Proposition 9.5.12.

Next, we look at the joint asymptotic distribution of these two variables as a $2 \times 1$ random vector, and use a dominated convergence theorem argument to show that they're are jointly independently normal. The delta method shows that the the numerator of 
$$
\tilde{M}_N^{1/2} \sum_{j=1}^{\tilde{M}_N} \frac{\tilde{\omega}^{N,j}}{\sum_{j'} \tilde{\omega}^{N,j'}}f(\tilde{\xi}^{N,j}_k) 
=
 \frac{ \tilde{M}_N^{1/2} \sum_{j=1}^{\tilde{M}_N} \frac{\tilde{\omega}^{N,j}}{\tilde{M}_N }f(\tilde{\xi}^{N,j}_k) }{ \frac{\sum_{j'} \tilde{\omega}^{N,j'}}{\tilde{M}_N} }
$$
is normal.

The denominator is consistent. Rewrite it as 

$$
 \tilde{M}_N^{-1}\sum_{j'}\left\{ \tilde{\omega}^{N,j'}-E[\tilde{\omega}^{N,j'}\mid \mathcal{F}^N_{k-1}] \right\} + \tilde{M}_N^{-1}\sum_{j'}E[\tilde{\omega}^{N,j'}\mid \mathcal{F}^N_{k-1}]
$$
The second piece converges to $\phi_{\nu, k-1}T_{k-1}^u( \mathsf{X})$ because we showed that $T_{k-1}^u(x, \mathsf{X}) \in L^1(\mathsf{X}, \phi_{\nu,k-1})$. The first piece converges due to Proposition 9.5.7.

Therefore, by Slutsky's theorem, 

$$
\tilde{M}_N^{1/2} \sum_{j=1}^{\tilde{M}_N} \frac{\tilde{\omega}^{N,j}}{\sum_{j'} \tilde{\omega}^{N,j'}}f(\tilde{\xi}^{N,j}_k)  \overset{\text{D}}{\to} \text{Normal}\left( \phi_{\nu,k}(f) , \frac{\sigma^2_{k-1}\left[ T_{k-1}^u \left( f - \phi_{\nu,k}(f) \right) \right] + \alpha^{-1}\eta^2_{k-1}\left[ \left( f - \phi_{\nu,k}(f) \right)^2  \right]}{\left(\phi_{\nu,k-1}T^u_{k-1}(\mathsf{X}) \right)^2}\right)
$$


## Step 2: Selection

Pick $f \in L^2(\mathsf{X}, \phi_{\nu,k})$ and write the target as 

$$
M_N^{1/2}\left\{M_N^{-1} \sum_{i=1}^{M_N} f(\xi^{N,i}_k) - E\left[ f(\xi^{N,i}_k) \mid \tilde{\mathcal{F}}^N_{k} \right]   \right\}
+
M_N^{1/2}\left\{M_N^{-1} \sum_{i=1}^{M_N} E\left[ f(\xi^{N,i}_k) \mid \tilde{\mathcal{F}}^N_{k} \right]   \right\}
$$

Focusing on the second piece first:

$$
M_N^{1/2} M_N^{-1} \sum_{i=1}^{M_N} E\left[ f(\xi^{N,i}_k) \mid \tilde{\mathcal{F}}^N_{k-1} \right] = M_N^{1/2}  E\left[ f(\xi^{N,1}_k) \mid \tilde{\mathcal{F}}^N_{k-1} \right] 
$$
due to the resampling being done conditionally independently and identically, and then

$$
M_N^{1/2}  E\left[ f(\xi^{N,1}_k) \mid \tilde{\mathcal{F}}^N_{k-1} \right] = M_N^{1/2}\tilde{M}_N^{1/2} \sum_{j=1}^{\tilde{M}_N} \frac{\tilde{\omega}^{N,j}}{\sum_{j'} \tilde{\omega}^{N,j'}}f(\tilde{\xi}^{N,j}_k)
$$

We showed this converges to a normal in the previous section. The first part of the sum

$$
M_N^{1/2}\left\{M_N^{-1} \sum_{i=1}^{M_N} f(\xi^{N,i}_k) - E\left[ f(\xi^{N,i}_k) \mid \tilde{\mathcal{F}}^N_{k} \right]   \right\}
$$

converges by Proposition 9.5.12. Jointly, the two summands are asymptotically indepdently normal, and using the delta method, we can prove the final result.

